service: pestico-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    COGNITO_USER_POOL_ID: us-east-1_i0CmHMrGQ
    COGNITO_CLIENT_ID: vbekr20j6fner6vhg66kp7nrn
    JWT_SECRET: "secret"
    MONGODB_URI: "mongodb+srv://shayan:whFQgge7Cv9ocfo8DYGE@pestico-manager.jaqcn3o.mongodb.net"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminUpdateUserAttributes
      Resource: "arn:aws:cognito-idp:us-east-1:270100954870:userpool/us-east-1_i0CmHMrGQ"

functions:
  app:
    handler: src/handlers/main.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
    role: arn:aws:iam::270100954870:role/pestico-api-dev-us-east-1-lambdaRole

package:
  individually: true

custom:
  esbuild:
    packager: "npm"
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node18"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
