service: pestico-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, env:STAGE, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}
    MONGODB_URI: ${env:MONGODB_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

functions:
  app:
    handler: src/handlers/main.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
    role: arn:aws:iam::270100954870:role/pestico-api-dev-us-east-1-lambdaRole

package:
  individually: true

custom:
  esbuild:
    packager: "npm"
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node18"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
