@apigw = https://xihg26vsr3.execute-api.us-east-1.amazonaws.com/dev
@local = http://localhost:3000

@endpoint = {{ local }}

### Register
POST {{ endpoint }}/auth/register
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "email": "testuser@example.ca",
  "password": "somelongpassword",
  "name": "Test User",
  "role": "admin",
  "status": "active",
  "address": "1234 Test St",
  "address2": "Apt 123",
  "city": "Test City",
  "postal_code": "12345",
  "phone": "123-456-7890"
}

### Login
POST {{ endpoint }}/auth/login
Content-Type: application/json

{
  "email": "somethingelse@post.ca",
  "password": "somelongpassword"
}
> {% client.global.set("token", response.body.token) %}

### Update User
PUT {{ endpoint }}/auth/6667a850ba71071b914c5264
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "customers": []
}